Bev/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_and_registration.urls', namespace='login')),
    url(r'^beverages/', include('apps.beverages.urls', namespace='beverages')),
    # url(r'^admin/', admin.site.urls),
]

apps/beverages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_form', views.add_form, name='add_form'),
    url(r'^add', views.add, name='add'),
    url(r'^edit/(?P<id>\d+)', views.edit, name='edit'),
    url(r'^distiller_info/(?P<id>\d+)', views.distiller_info, name='distiller_info'),
    url(r'^edit_distiller/(?P<id>\d+)', views.edit_distiller, name='edit_distiller'),
    url(r'^update_distiller/(?P<id>\d+)', views.update_distiller, name='update_distiller'),
    url(r'^delete/(?P<id>\d+)', views.delete, name='delete'),
    url(r'^delete_distiller/(?P<id>\d+)', views.delete_distiller, name='delete_distiller'),
    url(r'^favor/(?P<id>\d+)', views.favor, name='favor'),
    url(r'^review/(?P<id>\d+)', views.add_review, name='add_review'),
    url(r'^view/(?P<id>\d+)', views.show_review, name='show_review'),
    # url(r'^create_try/(?P<id>\d+)', views.create_try, name='create_try'),


]

apps/beverages/models.py
from __future__ import unicode_literals
from ..login_and_registration.models import User
from django.db import models
# V  https://docs.djangoproject.com/en/1.7/ref/models/queries/  V 'F' used to get the favor_point value incremented
from django.db.models import F
from django.db.models import Count

class BeverageManager(models.Manager):
    def create_beverage(self, request):
        errors = []
        if request.POST['name'] == "":
            errors.append('Whisky name cannot be empty')
            # return (False, errors)
        if request.POST['new_distiller_name'] == "" and request.POST['distiller_name'] == "":
            errors.append('You must either Enter or Select a Distiller Name')
            # return (False, errors)
        if request.POST['review'] == "":
            errors.append('Must type a Review!')
            # return (False, errors)
        if errors:
            return (False, errors)
        if request.POST['distiller_name'] == "":
            distiller = Distiller.objects.create(name_distiller=request.POST['new_distiller_name'])
        else:
            # request.POST['new_distiller_name'] == "":
            distiller = Distiller.objects.get(id=request.POST['distiller_name'])
        if not errors:
            # print 'No Errors!!'
            new_beverage = self.create(name=request.POST['name'], distiller=distiller,)
            return (True, new_beverage)
        else:
            return (False, errors)

    def delete_beverage(self, request, id):
        # print 'in model'
        # print 'self: ', self
        # print 'id: ', id
        Beverage.objects.get(id=id).delete()

    def favor_beverage_total(request, beverage_id):
        # favor_total = Beverage.objects.favor_total
        # if favor_total != 0:
        print beverage_id.id
        beverage_id = beverage_id.id
        Beverage.objects.filter(id=beverage_id).update(favor_total=F('favor_total')+1)
        # else:
        #     Beverage.objects.filter(id=beverage_id).update(favor_total=F('favor_total')+1)


class DistillerManager(models.Manager):
    def update_distiller(self, distiller_id, request):
        distiller = Distiller.objects.get(id=distiller_id)
        # print distiller
        distiller.name_distiller = request.POST['name_distiller']
        distiller.distiller_details = request.POST['distiller_details']
        distiller.save()

    def delete_distiller(self, request, id):
        Distiller.objects.get(id=id).delete()

    def exclude_current_distiller(self, distiller_id):
        distiller_id = distiller_id.id
        other_distillers = Distiller.objects.values().exclude(id=distiller_id)
        return other_distillers

# class TryManager(models.Manager):
#     def create_try(self, beverage_id, user_id):
#         pass

class ReviewManager(models.Manager):
    def add_review(self, request, bev_id):
        beverage_reviewed = Beverage.objects.get(id=bev_id)
        # print beverage_reviewed.id
        reviewer = User.objects.get(id=request.session['user']['user_id'])
        # print reviewer.id
        review = Review.objects.create(review_content=request.POST['review'], reviewer=reviewer, bev_reviewed=beverage_reviewed)

    def show_review(request, id):
        pass


class FavorPointManager(models.Manager):
    def create_favor(request, user_id, beverage_id):
        exists = FavorPoint.objects.filter(favor_user=user_id, favor_beverage=beverage_id)
        # , favor_point=request.POST['favor_point']+1
        if exists:
            FavorPoint.objects.filter(favor_user=user_id, favor_beverage=beverage_id).update(favor_point=F('favor_point')+1)
            # favor_count = FavorPoint.objects.annotate(num_favors=Count('favor_beverage')).filter(favor_beverage=beverage_id)
            # print favor_count[0].favor_point
            # return favor_count[0].favor_point
        else:
            FavorPoint.objects.create(favor_user_id=user_id, favor_beverage=beverage_id)

            # VV  works if there is only 1 beverage_id per single user, breaks if at least two users have favored
    def get_favor_count(request, user_id, beverage_id):
        # print 'beverage_id: ', beverage_id.id
        beverage_id = beverage_id.id
        favor_count = FavorPoint.objects.filter(favor_beverage=beverage_id).filter(favor_user=user_id).annotate(num_favors=Count('favor_beverage'))
        # favor_count = FavorPoint.objects.get(favor_beverage=beverage_id).annotate(num_favors=Count('favor_point'))
        # print '(user) favor points: ', favor_count[0].favor_point
        # return favor_count[0].favor_point
        return favor_count

class Distiller(models.Model):
    name_distiller = models.CharField(max_length=70)
    distiller_details = models.TextField(max_length=1000, default='details go here')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = DistillerManager()

class Beverage(models.Model):
    name = models.CharField(max_length=70)
    distiller = models.ForeignKey(Distiller)
    favor_total = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BeverageManager()

class Review(models.Model):
    reviewer = models.ForeignKey(User)
    review_content = models.CharField(max_length=500)
    bev_reviewed = models.ForeignKey(Beverage)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

class FavorPoint(models.Model):
    favor_user = models.ForeignKey(User, related_name='favor_user')
    favor_beverage = models.ForeignKey(Beverage, related_name='favor_beverage')
    favor_point = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = FavorPointManager()

# class Try(models.Model):
#     tried = models.BooleanField()
#     try_beverage = models.ForeignKey(Beverage)
#     try_user = models.ForeignKey(User)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     object = TryManager()

apps/beverages/views.py
from django.shortcuts import render, redirect
from ..login_and_registration.models import User
from models import Distiller, Beverage, FavorPoint, Review
from django.contrib import messages
from . import models
# from django.db.models import Lookup

def index(request):
    if 'user' in request.session:
        # beverage_id =
        context = {
            'whiskies': Beverage.objects.all().order_by('distiller__name_distiller'),
            'distillers': Distiller.objects.all(),
            'favor_pts': FavorPoint.objects.all().order_by('-created_at')[:3],
        }
        return render(request, 'beverages/index.html', context)
    return redirect('login:index')

def add_form(request):
    if 'user' in request.session:
        context = {
            'distillers': Distiller.objects.all(),
        }
        return render(request, 'beverages/add.html', context)
    return redirect('login:index')

def add(request):
    # print 'calling add method'
    # if 'user' in request.session:
    # print 'user in session'
    if request.method == 'POST':
        result = Beverage.objects.create_beverage(request)
        if result[0] == False:
            # print result[0], result[1]
            display_errors(request, result[1])
            return redirect('beverages:add_form')
        # print result[0]
        # print result[0], result[1].id
        Review.objects.add_review(request, result[1].id)
    return redirect('login:index')

def add_review(request, id):
    if 'user' in request.session:
        Review.objects.add_review(request, id)
        return redirect('beverages:show_review', id)
    return redirect('login:index')

def show_review(request, id):
    if 'user' in request.session:
        user_id = request.session['user']['user_id']
        context = {
            'whisky': Beverage.objects.get(id=id),
            'reviews': Review.objects.filter(bev_reviewed=id),
            'favor_points': FavorPoint.objects.filter(favor_beverage=id),
            'favor_points_by_user': FavorPoint.objects.filter(favor_beverage=id),
        }
        return render(request, 'beverages/review.html', context)
    return redirect('login:index')

def display_errors(request, display_errors_list):
    for error in display_errors_list:
        #  VV    https://docs.djangoproject.com/en/1.10/ref/contrib/messages/    VV
        messages.add_message(request, messages.INFO, error)

def edit(request, id):
    if 'user' in request.session:
        print id
        pass
    return redirect('login:index')

def distiller_info(request, id):
    # print 'distiller_info id: ', id
    this_distiller = Distiller.objects.get(id=id)
    context = {
        'this_distiller': this_distiller,
        'distillers': Distiller.objects.all(),
        'other_distillers': Distiller.objects.exclude_current_distiller(this_distiller),
    }
    return render(request, 'beverages/distiller.html', context)

def edit_distiller(request, id):
    if 'user' in request.session:
        context = {'this_distiller': Distiller.objects.get(id=id)}
        return render(request, 'beverages/edit_distiller.html', context)
    return redirect('login:index')

def update_distiller(request, id):
    if 'user' in request.session:
        if request.method == 'POST':
            Distiller.objects.update_distiller(id, request)
            # context = {'this_distiller': Distiller.objects.get(id=id)}
            return redirect('beverages:distiller_info', id)
    return redirect('LogReg:index')

def update_user(request, id):
    if user_in_session(request):
        if request.method == 'POST':
            User.objects.update_user(id, request)
            return redirect('/home')
    return redirect('LogReg:index')

def delete(request, id):
    if 'user' in request.session:
        # print 'in delete method'
        # print 'id:', id
        # if request.method == 'POST':
        Beverage.objects.delete_beverage(request, id)
        # print id
        # bev_id = Beverage.objects.delete_beverage(id, request)
        # print bev_id
    return redirect('login:index')

def delete_distiller(request, id):
    if 'user' in request.session:
        Distiller.objects.delete_distiller(request, id)
        # ha! exclude the chosen distiller, then redirect back to beverages:distiller_info...well...kinda ghetto forcing it back to id = 1 (Ardbeg) *****************
        return redirect('beverages:distiller_info', 1)
    return redirect('login:index')

# def create_try(request, id):
#     if 'user' in request.session:
#         # user = User.objects.get(id=id)
#         beverage = Beverage.objects.get(id=id)
#         print beverage
#         # print user
#         return render(request, 'beverages:index')

def favor(request, id):
    if 'user' in request.session:
        if request.method == 'POST':
            # Favor.objects.create_favor(request.session.user.id), request.POST['whisky.id']
            favor_user = request.session['user']['user_id']
            favor_beverage = Beverage.objects.get(id=id)
            # print 'user id: ', request.session['user']['user_id']
            # print 'favor_beverage: ', favor_beverage.id
            FavorPoint.objects.create_favor(favor_user, favor_beverage)
            Beverage.objects.favor_beverage_total(favor_beverage)
            # context = {
            #     'favor_user': request.session['user']['user_id'],
            #     'favor_pts': FavorPoint.objects.favor_point.filter(beverage_id=id),
            # }
            # context = {
            #     'whiskies': Beverage.objects.all(),
            #     'distillers': Distiller.objects.all(),
            #     'favor_pts': FavorPoint.objects.all().filter(favor_beverage__favor_beverage=id),
            # }
            # return render(request, 'beverages/index.html', context)
            # return render(request, 'beverages/index.html')
            return redirect('beverages:index')
        else:
            return redirect('beverages:index')
    return redirect('login:index')

apps/beverages/templates/beverages/add.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'beverages/css/styles.css' %}">
    </head>
    <body>
        <div id="wrapper-outer">
            <div id="wrapper-inner">
                <h5>User: {{ request.session.user.first_name }} {{ request.session.user.last_name }} ({{ request.session.user.email }})</h5>
                <h5><a href="{% url 'beverages:index' %}">Home</a> | <a href="/logout">Logout</a></h5>
                <h4>Hello {{ request.session.user.alias }}</h4>
                <h3>Add Whisky</h3>
                <h3>Add Review</h3>
                <form class="" action="{% url 'beverages:add' %}" method="post">
                    {% csrf_token %}
                    <p>
                        <label for="name">Whisky Name: </label>
                        <input type="text" name="name" value="">
                    </p>
                    <p>
                        <label for="new_distiller_name">(admin) Enter Distiller: </label>
                        <input type="text" name="new_distiller_name" value="">
                    </p>
                    <p>
                        <label for="distiller_name">Select Distiller: </label>
                        <select class="" name="distiller_name">
                            <option value=""></option>
                            {% for distiller in distillers %}
                                <option value="{{ distiller.id }}">{{ distiller.name_distiller }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    {% if messages %}
                        {% for message in messages %}
                            <p class="red">{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                    <p>
                        <label for="review">Review: </label>
                        <textarea name="review" rows="8" cols="80"></textarea>
                    </p>
                    <input type="submit" name="submit_new" value="Add Whisky and Review">
                    <a href="{% url 'beverages:index' %}">Cancel</a>
                    <!-- <form class="" action="{% url 'beverages:index' %}" method="get">
                        <input type="submit" name="" value="Cancel">
                    </form> -->
                </form>
            </div>
        </div>
    </body>
</html>

apps/beverages/templates/beverages/distiller.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Distiller</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'beverages/css/styles.css' %}">
    </head>
    <body>
        <div id="wrapper-outer">
            <div id="wrapper-inner">
                <h5>User: {{ request.session.user.first_name }} {{ request.session.user.last_name }} ({{ request.session.user.email }})</h5>
                <h5><a href="{% url 'beverages:index' %}">Home</a> | <a href="/logout">Logout</a></h5>
                <h4>Hello {{ request.session.user.alias }}</h4>
                <h3>Distiller: {{ this_distiller.name_distiller }}</h3>
                <h4>Information:</h4>
                <p>{{ this_distiller.distiller_details }}</p>

                <h3>Other Distillers</h3>
                <table>
                    <thead>
                        <th>Distiller</th><th>Action</th>
                    </thead>
                    <tbody>
                        {% for distiller in other_distillers %}
                            <tr>
                                <td><a href="{% url 'beverages:distiller_info' distiller.id %}">{{ distiller.name_distiller }}</a></td>
                                <td>
                                    <a href="{% url 'beverages:edit_distiller' distiller.id %}">Update</a> |
                                    <a href="{% url 'beverages:delete_distiller' distiller.id %}">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>

apps/beverages/templates/beverages/edit_distiller.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Update Distiller</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'beverages/css/styles.css' %}">
    </head>
    <body>
        <div id="wrapper-outer">
            <div id="wrapper-inner">
                <h5>User: {{ request.session.user.first_name }} {{ request.session.user.last_name }} ({{ request.session.user.email }})</h5>
                <h5><a href="{% url 'beverages:index' %}">Home</a> | <a href="/logout">Logout</a></h5>
                <h4>Hello {{ request.session.user.alias }}</h4>
                <h3>Update Distiller Form</h3>
                <h2>{{ this_distiller.name_distiller }}</h2>
                <form class="" action="{% url 'beverages:update_distiller' this_distiller.id %}" method="post">
                    {% csrf_token %}
                    <p>
                        <label for="name_distiller">Name: </label>
                        <input type="text" name="name_distiller" value="{{ this_distiller.name_distiller }}">
                    </p>
                    <p>
                        <label for="distiller_details">Details: </label>
                        <input type="text" name="distiller_details" value="{{ this_distiller.distiller_details }}">
                    </p>
                    <input type="submit" name="submit_changes" value="Update">

                </form>
            </div>
        </div>
    </body>
</html>

apps/beverages/templates/beverages/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Beverages</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'beverages/css/styles.css' %}">
    </head>
    <body>
        <div id="wrapper-outer">
            <div id="wrapper-inner">
                <h4>User: {{ request.session.user.first_name }} {{ request.session.user.last_name }} ({{ request.session.user.email }})</h4>
                <h4><a href="/logout">Logout</a></h4>
                <h3>Hello {{ request.session.user.alias }}</h3>
                <p class="font-size-85">Click on the Whisky in the table below to view other user reviews and add your own review.</p>
                <p class="font-size-85">Click on a Distiller for more information.</p>
                <p class="font-size-85">Click the '+1 Favor Pt' button as many times as you like to Favor that Whisky!  Personal Favor score is visible in the Whisky Review page.</p>
                <h1>Whisky and Bourbon Review</h1>
                <h4>Recent Reviews</h4>
                {% for favor_point in favor_pts %}
                    <p class="font-size-85 red">
                        {{ favor_point.favor_user.alias }} reviewed
                        {{ favor_point.favor_beverage.name }} and gave it
                        {{ favor_point.favor_point }} Favor Points {{ favor_point.created_at }}
                    </p>
                {% endfor %}
                <!-- <h4>Recent Favor Points</h4>
                {% for favor_point in favor_pts %}
                    <p class="font-size-85 red">
                        {{ favor_point.favor_user.alias }} has assigned
                        {{ favor_point.favor_point }} Favor Points to
                        {{ favor_point.favor_beverage.name }}
                    </p>
                {% endfor %} -->
                <p class="font-size-85 red">...</p>
                <p><a href="{% url 'beverages:add_form' %}">Add Whiskey and Review</a></p>
                <table>
                    <thead>
                        <th>Whisky</th><th>Distiller</th><th>Favor Pts</th><th>Action</th>
                    </thead>
                    <tbody>
                        {% for whisky in whiskies %}
                            <tr>
                                <td><a href="{% url 'beverages:show_review' whisky.id %}">{{ whisky.name }}</a></td>
                                <td><a href="{% url 'beverages:distiller_info' whisky.distiller.id %}">{{ whisky.distiller.name_distiller }}</a></td>
                                <td class="favor-cell">{{ whisky.favor_total }}</td>
                                <td>
                                    <a href="{% url 'beverages:delete' whisky.id %}" class="inline-it">Delete</a> |
                                    <form class="inline-it" action="{% url 'beverages:favor' whisky.id %}" method="post">
                                        {% csrf_token %}
                                        <!-- <a href="{% url 'beverages:favor' whisky.id %}">1 Favor Point</a> -->
                                        <input type="submit" name="" value="+1 Favor Pt">
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>

apps/beverages/templates/beverages/review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Review Time</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'beverages/css/styles.css' %}">
    </head>
    <body>
        <div id="wrapper-outer">
            <div id="wrapper-inner">
                <h5>User: {{ request.session.user.first_name }} {{ request.session.user.last_name }} ({{ request.session.user.email }})</h5>
                <h5><a href="{% url 'beverages:index' %}">Home</a> | <a href="/logout">Logout</a></h5>
                <h4>Hello {{ request.session.user.alias }}</h4>
                <h3>Leave your review for {{ whisky.name }} ({{ whisky.distiller.name_distiller }})</h3>
                <form class="" action="{% url 'beverages:add_review' whisky.id %}" method="post">
                    {% csrf_token %}
                    <label for="review">Add your Review: </label>
                    <textarea name="review" rows="8" cols="80"></textarea>
                    <input type="submit" name="" value="Submit Review">
                </form>
                <p>Reviews:</p>
                    {% for review in reviews %}
                        <div class="review-box">
                            <p>{{ review.review_content }}</p>
                            <p class="font-size-85">- a review by: {{ review.reviewer.alias }} ({{ review.reviewer.first_name }} {{ review.reviewer.last_name }})</p>
                            <p class="font-size-85">- {{ review.created_at }}</p>
                        </div>
                    {% endfor %}
                <p>Favored By:</p>
                    {% for user_point in favor_points_by_user %}
                        <p>- {{ user_point.favor_user.alias }} with <span class="red">{{ user_point.favor_point }}</span> favor point(s)</p>
                    {% endfor %}
                <!-- <a href="{% url 'beverages:add_review' whisky.id%}">Leave a Review</a> -->
            </div>
        </div>
    </body>
</html>