Bev/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_and_registration.urls', namespace='login')),
    url(r'^beverages/', include('apps.beverages.urls', namespace='beverages')),
    # url(r'^admin/', admin.site.urls),
]

apps/login_and_registration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^register$', views.register, name='register'),
    # url(r'^login$', views.login, name='login'),
    # # Dont' FORGET THE COMMAS!!!!! # #
    url(r'^register_login$', views.register_login, name='log_reg'),
    url(r'^home$', views.home, name='home'),
    url(r'^home/(?P<id>\d+)/delete$', views.delete, name='delete'),
    url(r'^home/(?P<id>\d+)/edit', views.edit, name='edit'),
    url(r'^home/(?P<id>\d+)/update_user', views.update_user, name='update_user'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^$', views.index, name='index'),
]

apps/login_and_registration/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
# from django.core.exceptions import ObjectDoesNotExist
import bcrypt
import re

from django.core.validators import RegexValidator

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'[a-zA-Z-]*[a-zA-Z-]+[a-zA-Z-]$')

class UserManager(models.Manager):
    def reg_validation(self, request):
        errors = []
        if not request.POST['first_name'] or not request.POST['last_name']:
            errors.append('- Both First and Last Name are required!')
        if len(request.POST['first_name']) < 2:
            errors.append('- First Name must be 2 or more characters!')
        if len(request.POST['last_name']) < 2:
            errors.append('- Last Name must be 2 or more characters!')
        if not NAME_REGEX.match(request.POST['first_name']) or not NAME_REGEX.match(request.POST['last_name']):
            errors.append('- Both First and Last Name must consist only of alpha characters (dash OK)')
        if len(request.POST['alias']) < 3:
            errors.append('- Alias must be at least 2 characters')
        if not request.POST['email']:
            errors.append('- Email is required!')
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append('- Email entered is invalid format - s/b: xxxx@xxxx.xxx')
        if len(request.POST['password']) < 8:
            errors.append('- Password must be at least 8 characters')
        if request.POST['password'] != request.POST['confirm_password']:
            errors.append('- Passwords must match!')
        if not errors:
            password = request.POST['password']
            pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
            user = self.create(
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                alias=request.POST['alias'],
                email=request.POST['email'],
                password=pw_hash,
            )
            return (True, user)
        else:
            print errors
            return (False, errors)

    def login_validation(self, request):
        errors = []
        try:
            user = User.objects.get(email=request.POST['email'])

            hashed = User.objects.get(email=request.POST['email']).password
            hashed = hashed.encode('utf-8')
            password = request.POST['password']
            password = password.encode('utf-8')
            if bcrypt.hashpw(password, hashed) == hashed:
            # password = request.POST['password'].encode()
                # print user.id, password
            # if bcrypt.hashpw(password, user.password.encode()):
                # print 'hashed: ', hashed
                return (True, user)
            else:
                errors.append('- Incorrect Email and/or Password')
                return (False, errors)
        except:
            errors.append('- Incorrect Email and/or Password')
            return (False, errors)

    def update_user(self, id, request):
        user = User.objects.get(id=id)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.alias = request.POST['alias']
        user.email = request.POST['email']
        user.save()


class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    alias = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login_and_registration/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User

def user_in_session(request):
    if 'user' in request.session:
        print 'method - user in sessions True!!'
        return True
    else:
        print 'method - user in sessions False!!'
        return False

def index(request):
    if user_in_session(request):
        # VV  this is where to plug-in the app  VV   *****
        return redirect('beverages:index')
    return render(request, 'login_and_registration/login.html')

def register_login(request):
    # if request.method == 'POST':
    if request.POST['action'] == 'register':
        result = User.objects.reg_validation(request)
    elif request.POST['action'] == 'login':
        result = User.objects.login_validation(request)
    if result[0] == False:
        # print 'logged-in? False - incorrect data'
        request.session['errors'] = result[1]
        context = { 'errors': request.session['errors'], }
        # print 'errors from register_login method view: ', errors
        return render(request, 'login_and_registration/login.html', context)
    # print result[1]
    return login_user(request, result[1])


def login_user(request, user):
    # print user
    request.session['user'] = {
        'user_id': user.id,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'alias': user.alias,
        'email': user.email,
        # 'users': User.objects.all(),
        # 'errors': errors,
    }
    # VV  this is where to plug-in the app  VV   *****
    # return redirect('LogReg:home')
    return redirect('beverages:index')

def home(request):
    if user_in_session(request):
        context = { 'users': User.objects.all(), }
        return render(request, 'login_and_registration/home.html', context)
    return redirect('LogReg:index')

def edit(request, id):
    user = User.objects.get(id=int(id))
    print user.id
    context = {'user':user}
    return render(request, 'login_and_registration/update.html', context)


def update_user(request, id):
    if user_in_session(request):
        if request.method == 'POST':
            User.objects.update_user(id, request)
            return redirect('/home')
    return redirect('LogReg:index')
    # return redirect('LogReg:index')

def delete(request, id):
    User.objects.filter(id=id).delete()
    return redirect('/home')

def logout(request):
    request.session.clear()
    return render(request, 'login_and_registration/login.html')

apps/login_and_registration/templates/login_and_registration/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home Page</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_and_registration/css/styles.css' %}">
    </head>
    <body>
        <h3>Welcome Home, {{ request.session.user.first_name }} {{ request.session.user.last_name}} - User#{{ request.session.user.user_id }}</h3>
        <h4><a href="/logout">Logout</a></h4>
        <!-- {% if reg_message %}<h3>{{ reg_message }}</h3>{% endif %} -->
        <!-- {% if login_message %}<h3>{{ login_message }}</h3>{% endif %} -->

        <table class="home">
            <thead>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Alias</th>
                <th>Email Address</th>
                <!-- <th>Password - remove</th> -->
                <th>Date Created</th>
                <th>Action</th>
            </thead>
            <tbody>
                <!--  pass in all users not just the NEW USER  -->
                {% for user in users %}
                    <tr>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name}}</td>
                        <td>{{ user.alias }}</td>
                        <td>{{ user.email }}</td>
                        <!-- <td>{{ user.password }}</td> -->
                        <td>{{ user.created_at }}</td>
                        <td><a href="/home/{{ user.id }}/delete">Remove</a> | <a href="{% url 'login:edit' user.id %}">Update</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

apps/login_and_registration/templates/login_and_registration/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login or Register</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_and_registration/css/styles.css' %}">
    </head>
    <body>
        <div id="wrapper">
            <h2>Registration and Login</h2>
            <h4>Register here:</h4>
            <form class="" action="/register_login" method="post">
                {% csrf_token %}
                <table>
                    <input type="hidden" name="action" value="register">
                    <tr><td>First Name:</td><td><input type="text" name="first_name" value="{{ new_user.first_name }}"></td></tr>
                    <tr><td>Last Name:</td><td><input type="text" name="last_name" value=""></td></tr>
                    <tr><td>Alias:</td><td><input type="text" name="alias" value=""></td></tr>
                    <tr><td>Email Address:</td><td><input type="text" name="email" value=""></td></tr>
                    <tr><td>Password:</td><td><input type="password" name="password" value=""></td></tr>
                    <tr><td>Confirm Password:</td><td><input type="password" name="confirm_password" value=""></td></tr>
                    <tr><td></td><td><input type="submit" name="" value="Register and Login"></td></tr>
                </table>
            </form>
            <p> - - - </p>
            <!-- {% if errors %} -->
                {% for error in request.session.errors %}
                    <p class="red">{{ error }}</p>
                {% endfor %}
            <!-- {% endif %} -->
            <p> - - - </p>
            <h4>Already Registered?  Login below:</h4>
            <form class="" action="/register_login" method="post">
                {% csrf_token %}
                <table>
                    <input type="hidden" name="action" value="login">
                    <tr><td>Email Address:</td><td><input type="text" name="email" value=""></td></tr>
                    <tr><td>Password:</td><td><input type="password" name="password" value=""></td></tr>
                    <tr><td></td><td><input type="submit" name="" value="Login"></td></tr>
                </table>
            </form>
        </div>
    </body>
</html>

apps/login_and_registration/templates/login_and_registration/update.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Update User</title>
    </head>
    <body>
        <h2>Update User: {{ user.first_name }} {{ user.last_name }}</h2>
        <form class="" action="{% url 'login:update_user' user.id %}" method="post">
            {% csrf_token %}
            <p>
                <label for="first_name">First Name: </label>
                <input type="text" name="first_name" value="{{ user.first_name }}">
            </p>
            <p>
                <label for="last_name">Last Name: </label>
                <input type="text" name="last_name" value="{{ user.last_name }}">
            </p>
            <p>
                <label for="last_name">Alias: </label>
                <input type="text" name="alias" value="{{ user.alias }}">
            </p>
            <p>
                <label for="email">Email: </label>
                <input type="text" name="email" value="{{ user.email }}">
            </p>
            <input type="submit" name="submit_update" value="Update">
        </form>
    </body>
</html>